name: Pre Deployment

on:
  push:
    branches:
      - main
      - develop
      - release
  pull_request:
    branches:
      - main
      - develop
      - release

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment:
      name: betty-secret
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install git-crypt
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git-crypt

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 -d | gpg --import

      - name: Unlock git-crypt files
        run: |
          git-crypt unlock
          git-crypt status

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build
        run: go build -v ./...

      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: ./config/config.yaml
